### ISSUE TITLE
Guidance to carry on the implementation

### ISSUE THREAD

**Issue by Ysmita** [klickmal/ContextNet#2]
Hi @klickmal , 
I am very much interested in your work. I would like to implement this. But I don't know how to go ahead as there is no proper Readme file. It would be very helpful if you would provide me with the flow of how to implement this.
Thanking you in anticipation.

**Comment by klickmal** [comment]
Hi @Ysmita ,

thanks for your message. Keras 2.0.6 is used in the code. I have made a little change in the convolutional.py of keras. So you should replace the corresponding file in "<Your PYTHON 3.6>\Lib\site-packages\keras\layers". And download dataset cityscapes, then put them in the directory structure of data file. At last run the file "train_test.py".

And I implemented the code to practice programming. I trained the model only with a subset of dataset in a few epochs because of lack of graphic card.  You should check if the model can work well.
